import type { BudgetTemplateSection } from '../types';

export const DEFAULT_BUDGET_TEMPLATE_SECTIONS: BudgetTemplateSection[] = [
  {
    id: 1,
    title: 'Projeto Arquitetônico',
    unit: 'h',
    billing: { method: 'per_hour', value: 69.15 },
    items: [
      {
        id: 1,
        description: 'Estudo Preliminar e de Viabilidade',
        quantity: 1,
        unitPrice: 30,
        estimatedHours: 0,
      },
      { id: 2, description: 'Anteprojeto', quantity: 1, unitPrice: 30, estimatedHours: 0 },
      {
        id: 3,
        description: 'Projeto Legal (Aprovação na Prefeitura)',
        quantity: 1,
        unitPrice: 30,
        estimatedHours: 0,
      },
      {
        id: 4,
        description: 'Projeto Executivo de Arquitetura',
        quantity: 1,
        unitPrice: 30,
        estimatedHours: 0,
      },
      {
        id: 10,
        description: 'Compatibilização de Projetos Complementares',
        quantity: 1,
        unitPrice: 30,
        estimatedHours: 0,
      },
    ],
  },
  {
    id: 5,
    title: 'Design de Interiores',
    unit: 'm²',
    billing: { method: 'percentage_on_top', value: 20 },
    items: [
      {
        id: 11,
        description: 'Layout e Estudo de Fluxo',
        quantity: 80,
        unitPrice: 40,
        estimatedHours: 16,
      },
      {
        id: 12,
        description: 'Projeto de Gesso e Iluminação (Luminotécnico)',
        quantity: 80,
        unitPrice: 35,
        estimatedHours: 20,
      },
      {
        id: 13,
        description: 'Projeto de Paginação de Pisos e Revestimentos',
        quantity: 80,
        unitPrice: 30,
        estimatedHours: 18,
      },
      {
        id: 14,
        description: 'Detalhamento de Marcenaria e Mobiliário Planejado',
        quantity: 4,
        unitPrice: 1200,
        estimatedHours: 40,
      },
      {
        id: 15,
        description: 'Seleção de Acabamentos, Metais e Louças',
        quantity: 1,
        unitPrice: 3000,
        estimatedHours: 12,
      },
      {
        id: 16,
        description:
          'Decoração e Produção de Ambientes (Seleção de móveis soltos, tapetes, cortinas)',
        quantity: 16,
        unitPrice: 200,
        estimatedHours: 16,
      },
    ],
  },
  {
    id: 2,
    title: 'Projetos Complementares',
    unit: 'vb',
    billing: { method: 'percentage_on_top', value: 15 },
    items: [
      { id: 5, description: 'Projeto Estrutural', quantity: 1, unitPrice: 8500, estimatedHours: 0 },
      {
        id: 6,
        description: 'Projeto Elétrico e de Automação',
        quantity: 1,
        unitPrice: 6000,
        estimatedHours: 0,
      },
      {
        id: 7,
        description: 'Projeto Hidrossanitário e Gás',
        quantity: 1,
        unitPrice: 6000,
        estimatedHours: 0,
      },
      {
        id: 17,
        description: 'Projeto de Paisagismo',
        quantity: 100,
        unitPrice: 20,
        estimatedHours: 15,
      },
    ],
  },
  {
    id: 3,
    title: 'Gerenciamento de Obra',
    unit: 'h',
    billing: { method: 'percentage_on_top', value: 18 },
    items: [
      {
        id: 8,
        description: 'Acompanhamento e Gestão de Obra',
        quantity: 40,
        unitPrice: 160,
        estimatedHours: 40,
      },
      {
        id: 9,
        description: 'Orçamentação Detalhada de Execução',
        quantity: 1,
        unitPrice: 2800,
        estimatedHours: 18,
      },
      {
        id: 18,
        description: 'Cronograma Físico-Financeiro',
        quantity: 1,
        unitPrice: 1500,
        estimatedHours: 10,
      },
      {
        id: 19,
        description: 'Seleção e Cotação de Fornecedores',
        quantity: 10,
        unitPrice: 120,
        estimatedHours: 10,
      },
    ],
  },
  {
    id: 4,
    title: 'Consultoria e Serviços Adicionais',
    unit: 'un',
    billing: { method: 'percentage_on_top', value: 25 },
    items: [
      {
        id: 20,
        description: 'Visita Técnica Avulsa',
        quantity: 1,
        unitPrice: 450,
        estimatedHours: 3,
      },
      {
        id: 21,
        description: 'Maquete Eletrônica / Renderização 3D (por imagem)',
        quantity: 5,
        unitPrice: 800,
        estimatedHours: 8,
      },
      {
        id: 22,
        description: 'Regularização de Imóvel',
        quantity: 1,
        unitPrice: 4000,
        estimatedHours: 25,
      },
      {
        id: 23,
        description: 'Laudo Técnico de Reforma (ART/RRT)',
        quantity: 1,
        unitPrice: 1200,
        estimatedHours: 5,
      },
    ],
  },
];
